handle jq command correctly

diff --git a/.github/workflows/pypi-whl.yml b/.github/workflows/pypi-whl.yml
--- a/.github/workflows/pypi-whl.yml
+++ b/.github/workflows/pypi-whl.yml
@@ -69,10 +69,18 @@ jobs:
         working-directory: .
         run: |
           # Check if the tag is a release version tag
-          if jq -e ".version[:1] != \"v\" and .version==\"$TAG\"" deno.json; then 
+          jq -e ".version[:1] != \"v\" and .version==\"$TAG\"" deno.json
+          ret=$?
+          if [ $ret -eq 0 ]; then
+              # Tag is a release version tag
               twine upload --verbose --repository testpypi dist/*.whl
-          else
+          elif [ $ret -eq 1 ]; then
+              # Tag is not a release version tag
               echo "Not releasing ($TAG is not a release version tag)"
+          else
+              # jq command failed
+              echo "jq command failed with exit code $ret"
+              exit $ret
           fi
         env:
           TWINE_USERNAME: __token__
